# Generated by Django 4.2.17 on 2025-01-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='business_type',
        ),
        migrations.AlterField(
            model_name='buyer',
            name='business_type',
            field=models.CharField(max_length=100),
        ),
    ]
