# Generated by Django 4.2.18 on 2025-02-01 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_seller_business_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='business_name',
            new_name='email',
        ),
    ]
