# Generated by Django 4.2.18 on 2025-02-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_category_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products/default_image.jpg', upload_to='products/'),
        ),
    ]
