# Generated by Django 5.1.6 on 2025-04-18 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_cart_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='selected_pincodes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
