# Generated by Django 4.2.17 on 2025-02-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='phone_number',
            new_name='contact_number',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='business_type',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='district',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='location',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='shop_name',
        ),
        migrations.AddField(
            model_name='buyer',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyer',
            name='password',
            field=models.CharField(default=12345678, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyer',
            name='username',
            field=models.CharField(default='default_username', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
