# Generated by Django 4.2.17 on 2025-02-10 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='password',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='username',
        ),
    ]
